// Generated by Wrangler on Mon Jul 08 2024 15:02:31 GMT+0930 (Australian Central Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	DATABASE: D1Database;
	ARGON2: Fetcher;
}
