#:schema node_modules/wrangler/config-schema.json
name = "saaskit"
compatibility_date = "2024-07-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DATABASE"
database_name = "data"
database_id = "6cea6a34-6b69-4dad-92dc-83e0de0655fc"
