import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import { getAuth } from '@/lib/auth';
import { AuthProvider } from '@/context/auth';
import dynamic from 'next/dynamic';
import { DomainProvider } from '@/context/domain';
import TanstackProvider from '@/components/tanstack-provider';
import { I18nProviderClient } from '@/locales/client';
import { Toaster } from '@/components/ui/sonner';
import { AccessControlProvider, useAccessControl } from '@/context/access-control';

const inter = Inter({ subsets: ['latin'] });

export const runtime = 'edge';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const GlobalCommandMenu = dynamic(
  () => import('@/components/global-command-menu').then((mod) => ({ default: mod.GlobalCommandMenu })),
  {
    ssr: false,
  },
);

export default async function RootLayout({
  children,
  params: { domain, locale },
}: Readonly<{
  children: React.ReactNode;
  params: {
    domain: string;
    locale: 'en' | 'fr';
  };
}>) {
  const auth = await getAuth();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <DomainProvider value={domain}>
          <AuthProvider value={auth}>
            <AccessControlProvider>
              <I18nProviderClient locale={locale}>
                <TanstackProvider>
                  <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                    <main className="flex flex-col min-h-screen max-w-full overflow-hidden">
                      <div className="flex flex-col gap-4">{children}</div>
                    </main>
                    <Toaster />
                    <GlobalCommandMenu />
                  </ThemeProvider>
                </TanstackProvider>
              </I18nProviderClient>
            </AccessControlProvider>
          </AuthProvider>
        </DomainProvider>
      </body>
    </html>
  );
}
